import React from 'react';
import { Collapse } from 'antd';
const guide = (
  <div  className="tabContent" style={{ padding: '0 0%' }}>
    <h1 style={{ color: '#9EDDFF' }}>personnel Guide</h1>
    <h2>Making Reports</h2>
    <p>
      Reports can be booked in the 'Create  Report' Tab, which is the first place this application takes you when you log in. By default, there is an already-open report card.
    </p>
    <p>
      'Date' indicates the date in your current working repository / and not necessarily the current date.
    </p>
    <p>
      Select the patients involved by clicking on them. You can search, sort, and filter patients based on various selections of your own making (via the Editor) and choosing. These filters also serve to categorize your reports so that they can easily be organized, rowdiness removed, and events involving them can be followed.
    </p>
    <p>
      Enter the Title for the report and completely fillout the details.
    </p>
    <p>
     Select how each participant is affected by the described report by specfying parameter changes.
    </p>
    <p>
      Transfer Items/Titles between patients when a Holder is a selected participant.
    </p>
    <p>
      Indicate the duration of the report by using the time module.
    </p>
    <p>
      After the 'Submit Report' button is pressed, the segments panel will be removed, and you can choose to add another by clicking the 'Add Report' button, or you can check out the 'Reader Tab' to view your logs.
    </p>

    <h2>Medical Records Tab</h2>
    <p>
      The Medical Records is where you can read and review your reports and those of others. Follow up on specific cases based on the categories you have.
    </p>
    <p>
      Click on the 'Data Repository' header to reveal a panel that contains the top 10 in their respective categories. Click on one to see a preview.
    </p>
    <p>
      When previewing an option, tap on 'View Post,' and you will notice that your data (patients, Items, Parameter Perception, Main Logs, etc.) will temporarily be replaced by the Data Entry you review. This means that you can now read that poster's stories with a better understanding because of the access you have to their patients, items, categories, etc. It is easier to understand what's important in the context of the poster's Entry. You can then follow specific histories by filtering by categories and specific patients.
    </p>
    <p>
      NB: It is possible to copy the previewed Entries category, patients, and items (This feature hase been created to maximize accountability and combat situations such as data loss or corruption). This will permanently replace yours.
    </p>
    <p>
      You can, of course, publish and update your Repo by pushing the 'Publish My Database' button.
    </p>

    <h2>The Editor</h2>
    <p>
      The Editor Tab is where you can add, modify, and delete elements of the database. Double-tap on a cell to edit its value/name. Most changes will be reflected in your repository immediately. Changes automatically save after you edit, but if you notice it doesn't, manually click the 'Save' button at the top right of the screen.
    </p>

    <h2>Medical Events</h2>
    <p>
    a dedicated space within our application designed to monitor and manage critical health parameters. We understand the significance of timely notifications when it comes to maintaining optimal health, and this tab serves as your proactive health companion.
    </p>
  
    {/* <p>
      <strong>USING THE EVENT GENERATOR:</strong> The event Generator is divided into two parts: 1. Requirements (conditions to be met before the event can occur) 2. Consequences (The Changes to the involved participant(s) when these events happen.)
    </p> */}
    <p>
      The event text (that indicates when an event has happened) will appear in the Notifications Tab. The body of the event text is generated by combining the: Event Description + Affected Participant (computer-selected) + Consequences Description.
    </p>
    <>For more Q & A you can contact me directly ;)</>
  </div>
);

const aim = (
  <div  className="tabContent" style={{ padding: '0 0%' }}>
    <h1 style={{ color: '#9EDDFF' }}>Work In Progress</h1>
  

    <h1>Welcome to MediConnect</h1>
    <p>Creating a database of patients for small hospitals & clinics to work with, with individual personnel repositories to facilitate a truly separate workspace while keeping the collaborative spirit.</p>

    <h2>Key Features:</h2>
    <ul>
        <li>Centralized Patient Database</li>
        <li>Individual Personnel Repositories</li>
        <li>Collaborative Workspace</li>
        <li>Efficient Patient Management</li>
        <li>Streamlined Clinic Operations</li>
    </ul>

    <p>At MediConnect, our aim is to provide small hospitals and clinics with a powerful tool for managing patient information efficiently. The individual personnel repositories ensure that each member of the healthcare team has their dedicated workspace, fostering collaboration while maintaining privacy and organization.</p>

    <p>Take advantage of MediConnect's features to streamline clinic operations and enhance patient care. Welcome to a new era of healthcare management!</p>

    <p>
      Ultimately, I'm creating this web app to address my own pain points as a reader and wrestling aficionado. In the nearest future (I hope), it will serve as a platform for creating and reading fantasy bookings in a way that enables both the reader and creator to explore a wider range of stories in one place without the loss of context that long bookings often suffer from.
    </p>
  </div>
);

    
  const items = [
    {
      key: '1',
      label: <h2>Guide</h2>,
      children: <div style={{ padding: '0 10%' }}>{guide}</div>,
    },
    {
      key: '2',
      label: <h2>The Ultimate Aim of BookBoard</h2>,
      children: <div style={{ padding: '0 10%' }}>{aim}</div>,
    },
  ];
  
  const About = () => (
    <div style={{ padding: '0 20%' }}>
      <Collapse items={items} bordered={false} />
    </div>
  );
  
export default About;